[profile.default]
src = "src"
out = "out"
test = "test/unit"

[profile.mainnet]
fork_url = "https://rpc.ankr.com/eth"
optimizer = true
optimizer_runs = 200
test = "test/mainnet"

[profile.bsc]
fork_url = "https://rpc.ankr.com/bsc"
optimizer = true
optimizer_runs = 200
test = "test/bsc"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
